# Ansible inventory file
all:
  hosts:
    windows_server_1:
      ansible_host: 192.168.1.10
      ansible_user: "{{ windows_servers[0].user }}"
      ansible_password: "{{ windows_servers[0].password }}"
    windows_server_2:
      ansible_host: 192.168.1.11
      ansible_user: "{{ windows_servers[1].user }}"
      ansible_password: "{{ windows_servers[1].password }}"

    windows_10_server_1:
      ansible_host: 192.168.1.20
      ansible_user: "{{ windows_10_servers[0].user }}"
      ansible_password: "{{ windows_10_servers[0].password }}"
    windows_10_server_2:
      ansible_host: 192.168.1.21
      ansible_user: "{{ windows_10_servers[1].user }}"
      ansible_password: "{{ windows_10_servers[1].password }}"

    ubuntu_server_1:
      ansible_host: 192.168.1.12
      ansible_user: "{{ ubuntu_servers[0].user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_path }}"
    ubuntu_server_2:
      ansible_host: 192.168.1.13
      ansible_user: "{{ ubuntu_servers[1].user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_path }}"

    kali_linux:
      ansible_host: 192.168.1.14
      ansible_user: "{{ kali_linux.user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_path }}"
